### ISSUE TITLE
关于linearfitplot

### ISSUE THREAD

**Issue by QianyaoZ** [ChineseCricket/ExpDataAnalysis-Python#2]
在进行线性拟合的时候，数据不变，为什么阴影部分的"errobar"会变化那么大呢？
还有进行不确定度报告的时候为什么显示两个测量量的自由度为0？

**Comment by ChineseCricket** [comment]
> 在进行线性拟合的时候，数据不变，为什么阴影部分的"errobar"会变化那么大呢？ 还有进行不确定度报告的时候为什么显示两个测量量的自由度为0？

这个包中线性拟合的作图程序完全采用了seaborn的线性拟合作图，其内部程序为一黑箱，作者完全没有公布过源码，也没有这方面的计划，因此一直无法得知阴影部分的画法，考虑采用了类似人工智能的方法。目前一般建议使用该函数作图时多运行几次来得到效果比较好阴影部分——事实上每一组拟合的阴影部分也就只有非常少的几个可能绘制结果，试几遍总是可以找到看着比较合理的。
关于不确定度报告中的自由度，如果是作为测量列L给入的数据，则在测量列只有一个数时，自由度会被判断为0（唯一的自由度已经消耗在于求平均值产生的约束中，虽然此时的平均值并没有意义）。因此如果想要传入一个常数或者由其他测量确定的数，请考虑使用UncertaintyReport函数的exData变量传入，传入格式已经写在程序注释中，此时会要求给出传入数的标准不确定度和自由度：如果为常数，请将标准不确定度填为0，自由度填一个非常大的数即可。

**Comment by QianyaoZ** [comment]
啊这边现在的情况是：测量列给入的数据为4个，但得到的结果自由度为0耶（但现在复刻不了了，应该是我无意中de掉了一个bug，大概率是没什么问题了）

**Comment by ChineseCricket** [comment]
> 啊这边现在的情况是：测量列给入的数据为4个，但得到的结果自由度为0耶（但现在复刻不了了，应该是我无意中de掉了一个bug，大概率是没什么问题了）

没有BUG就好。
